language: ruby
cache:
  npm:     true
  bundler: true
  directories:
  - node_modules

node_js:
- 10.3.0

install:
- npm install
- bundle install --without production --deployment

before_install:
- gem install bundler

script:
- bundle exec rake assets:precompile
- bundle exec rake test SKIP_BUILD=1
- bundle exec rspec spec/qiita.rb

#deploy:
#  provider: heroku
#  api_key:
#    secure: E9u0zceBt9hycppCOG17ZT6UIzdWbUDf0FxmRPIcjw3Oy4UQvFd8992ocGGbCdIVNJVUQLse7rXcNZME7yDVEXtDsoekMUx5ZHiBq+/ELJPwsutK4wU+jrn1CrQFrsGbEqJ0HlxyBinzBFu9H1IFezLRCYuK1zFhwebIojIlgeY=
#  app:
#    master: yasslab-jp

# Notify results to Idobata.io (Outdated)
#notifications:
#  webhooks:
#    secure: "k3OnnsbFwqoQyL+f4I+IE1/DEGlrIJ/YqfMSBunKczcKEaFRQJZ4ZZWMEKlRyAArWmPPKOkXuHS6Ke28RSOyLaSfe31beQvFsHCZJcptJWZ7M++fu0xMwRVBCOsPlmN3HSNzJ1S2JiW9Eg2cARI37iYq1q45eejKK5vitA5bxrc="

# Only run tests when master branch changes
# or when a PR branch is updated.
branches:
  only:
  - master
