# URL settings for yasslab.jp
permalink: /:title
url: https://yasslab.jp

# URL settings for Posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: /ja/news/:title

# Use sass for designing
sass:
  style:     compact
  sass_dir:  css
  sourcemap: always
  load_paths:
    - _sass
    - node_modules

# Variables for pages, posts, feeds, etc
company:
  vision: "Having a Good Life with OpenSource ;)"
  size: 12
  email: info@yasslab.jp
  capital: 500
  name:  YassLab
  description: "100% Remote Work company based in Okinawa & Tokyo, focusing on Ruby/Rails Web Development, Education, and OpenSource."
  ja:
    name: YassLab 株式会社
    description: "沖縄と東京を拠点にしたソフトウェア開発会社です。RailsチュートリアルやRailsガイドを運営し、月額制開発支援サービスも提供しています。"
  en:
    name: YassLab Inc.
    description: "100% Remote Work company based in Okinawa & Tokyo, focusing on Ruby/Rails Web Development, Education, and OpenSource."

# Variables to configure RSS feed
authors:
  yasulab:
    name: yasulab
    uri:  https://twitter.com/yasulab
  Yuppyhappytoyou:
    name: Yuppyhappytoyou
    uri:  https://twitter.com/Yuppyhappytoyou

# Settings for Jekyll/Heroku hosting
domain:   "yasslab.jp"
source:      ./
destination: ./_site
timezone: Asia/Tokyo
encoding: utf-8

# Show upcoming posts (but hidden in production)
future: true

## Global Vars to generate links
yasslab:       "[YassLab](https://yasslab.jp/)"
railstutorial: "[Railsチュートリアル](https://railstutorial.jp/)"
railsguides:   "[Railsガイド](https://railsguides.jp/)"
coderdojo:     "[coderdojo.jp](https://coderdojo.jp/)"
okinawarb:     "[Okianwa.rb](https://ruby.okinawa/)"
frogs:         "[Ryukyufrogs](https://www.ryukyu-frogs.com/)"

highlighter: rouge
markdown: kramdown
kramdown:
  auto_ids      : true
  autolink      : true
  entity_output : as_char
  toc_levels    : 1..6
  smart_quotes  : lsquo,rsquo,ldquo,rdquo
  input         : GFM
  gfm_quirks    : paragraph_end
  hard_wrap     : true
  footnote_nr   : 1
  show_warnings : false

plugins: 
  - kramdown
  - jekyll-gist
  - jekyll-coffeescript
  - jekyll-assets
  - jekyll-include-cache
  - qiita

exclude:
  - README.md
  - Procfile
  - Gemfile
  - Gemfile.lock
  - config.ru
  - vendor
  - app.json
  - node_modules
  - package.json
  - package-lock.json
  - test
  - spec
  - .jekyll-cache

# Enable Incremental Regeneration feature (experimental)
# https://jekyllrb.com/docs/configuration/incremental-regeneration/
#
# Disabled; needed to rebuild all pages to show future posts.
# But you can enable this feature by adding '--incremental' option.
incremental: false
