name: Test & Deploy
on: [push]
#on:
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2-beta
      with:
        node-version: '12'

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        #ruby-version: 2.6 # Not needed with a .ruby-version file

    - name: Install dependencies
      run: |
        npm install
        bundle install

    - name: bundle exec rake assets:precompile
      run:  bundle exec rake assets:precompile
    - name: bundle exec rake test SKIP_BUILD=1
      run:  bundle exec rake test SKIP_BUILD=1
    - name: bundle exec rspec spec/qiita.rb
      run:  bundle exec rspec spec/qiita.rb

    - name: actions-idobata
      uses: mahaker/actions-idobata@v1.1.1
      with:
        hookUrl: ${{ secrets.IdobataHookUrl }}
        message: | # multiple lines
          <div>
          CI build for ${{ github.event_name }} event : <span class='label label-${{ job.status }}'>${{ job.status }}</span> (<a href='https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'>Actions</a>)<br>
          <a href='https://github.com/${{ github.repository }}/commit/${{ github.sha }}'>Commit</a> to <a href='https://github.com/${{ github.repository }}'>${{ github.repository }}</a> by <a href='https://github.com/${{ github.actor }}'>${{ github.actor }}</a>.
          </div>
        format: 'html' # default

    - name: Deploy to Heroku
      env:
        HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
        HEROKU_APP_NAME: "yasslab-jp"
      if: github.ref == 'refs/heads/master' && job.status == 'success'
      run: git push https://heroku:$HEROKU_API_TOKEN@git.heroku.com/$HEROKU_APP_NAME.git origin/master:master
