name: Test & Deploy
on: [push]
#on:
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        #ruby-version: 2.7 # Not necessary if .ruby-version is given

    - name: 'Install dependencies'
      run: |
        npm install
        bundle config set path 'vendor/bundle'
        bundle install --jobs 4 --retry 3

    - name: 'Generate files and test them statically'
      run: |
        bundle exec rake assets:precompile
        bundle exec rake test SKIP_BUILD=1
        bundle exec rspec spec/qiita.rb

    - name: 'Deploy to Heroku if test suite passed'
      env:
        HEROKU_API_KEY:   ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP_NAME: 'yasslab-jp'
      if: github.ref == 'refs/heads/master' && job.status == 'success'
      run: |
        git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git origin/master:master

#    - name: actions-idobata
#      uses: mahaker/actions-idobata@v1.1.1
#      with:
#        hookUrl: ${{ secrets.IDOBATA_GITHUB_ACTIONS }}
#        message: | # multiple lines
#          <div>
#          CI build for ${{ github.event_name }} event : <span class='label label-${{ job.status }}'>${{ job.status }}</span> (<a href='https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'>Actions</a>)<br>
#          <a href='https://github.com/${{ github.repository }}/commit/${{ github.sha }}'>Commit</a> to <a href='https://github.com/${{ github.repository }}'>${{ github.repository }}</a> by <a href='https://github.com/${{ github.actor }}'>${{ github.actor }}</a>.
#          </div>
#        format: 'html' # default

