name: Test & Deploy
on: [push]
#on:
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        #ruby-version: 2.7 # Not necessary if .ruby-version is given

    - name: 'Install dependencies'
      run: |
        npm install
        bundle config set path 'vendor/bundle'
        bundle install --jobs 4 --retry 3

    - name: 'Generate files and test them statically'
      run: |
        bundle exec rake assets:precompile
        bundle exec rake test SKIP_BUILD=1
        bundle exec rspec spec/qiita.rb

    - name: 'Get commit info'
      run: |
        echo ::set-env name=COMMIT_MESSAGE::$(git log --format=%B -n 1 ${{ github.event.after }})
    - name: 'Notify test results to Idobata'
      uses: mahaker/actions-idobata@v1.1.1
      with:
        hookUrl: ${{ secrets.IDOBATA_GITHUB_ACTIONS }}
        format: 'html'
        message: |
          <div>
          CI build in <a href='https://github.com/${{ github.repository }}'>${{ github.repository }}</a> : <span class='label label-${{ job.status }}'>${{ job.status }}</span> (<a href='https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'>Actions</a>)<br>
          <img src='${{ github.event.organization.avatar_url }}'> <a href='https://github.com/${{ github.actor }}'>${{ github.actor }}</a> pushed <a href='https://github.com/${{ github.repository }}/commit/${{ github.sha }}'>${{ env.COMMIT_MESSAGE }}</a>
          </div>

    - name: 'Deploy to Heroku if test suite passed'
      if: github.ref == 'refs/heads/master' && job.status == 'success'
      uses: akhileshns/heroku-deploy@v3.4.6
      with:
        branch:          'master'
        heroku_api_key:   ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: 'yasslab-jp'
        heroku_email:    'yohei@yasslab.jp'
        usedocker:       false

