name: Scheduler to upsert News articles

# https://docs.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule
on:
  schedule:
    - cron:  '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        #ruby-version: 2.6 # Not needed with a .ruby-version file

    - name: bundle install
      run:  bundle install --path vendor/bundle --jobs 4 --retry 3
    - name: bundle exec rake upsert_recent_notes
      run:  bundle exec rake upsert_recent_notes

    - name: Commit new article(s) from Note RSS if exists
      run: |
        git config user.name  ${USERNAME}
        git config user.email ${EMAIL}
        git remote set-url origin https://${USERNAME}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
        git checkout master
        git add _data/news.yml
        git commit -m '🤖 Upsert note article(s) by GitHub Actions'
        git push origin HEAD
      env:
        USERNAME:     yasulab
        EMAIL:        yohei@yasslab.jp
        GITHUB_TOKEN: 

    - name: actions-idobata
      uses: mahaker/actions-idobata@v1.1.1
      with:
        hookUrl: ${{ secrets.IdobataHookUrl }}
        message: | # multiple lines
          <div>
          Test notification from Scheduler workflow in GitHub Actions. (<a href='https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'>Actions</a>)
          </div>
        format: 'html' # default
