name: Scheduled tasks to run every 30 minutes

# https://docs.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule
on:
  schedule:
    - cron:  '*/30 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        #ruby-version: 2.6 # Not needed with a .ruby-version file

    - name: Install Ruby gems dependencies
      run:  bundle install --path vendor/bundle --jobs 4 --retry 3
    - name: Upsert recent articles from note.com
      run:  bundle exec rake upsert_recent_notes
    - name: Share fetched articles from RSS
      run:  bundle exec rake share_rss_articles
      env:
        IDOBATA_SHARE: ${{ secrets.IDOBATA_SHARE }}
    - name: Share daily updates in Gumroad by using Emoji
      run: bundle exec rake share_gumroad_updates
      env:
        IDOBATA_GUMROAD:      ${{ secrets.IDOBATA_GUMROAD }}
        GUMROAD_ACCESS_TOKEN: ${{ secrets.GUMROAD_ACCESS_TOKEN }}
    - name: Share opt-in Health Planet user record (yasulab)
      run: bundle exec rake share_health_planet USER_NAME=yasulab LABEL_COLOR=label-info
      env:
        IDOBATA_HEALTH:      ${{ secrets.IDOBATA_HEALTH }}
        HEALTH_PLANET_TOKEN: ${{ secrets.HEALTH_PLANET_TOKEN }}
    - name: "Share inquiry from yasslab.jp"
      run: bundle exec rake share_inquiry
      env:
        IDOBATA_MAILS:       ${{ secrets.IDOBATA_MAILS  }}
        GMAIL_PASSWORD:      ${{ secrets.GMAIL_PASSWORD }}
        GMAIL_USERNAME:      ${{ secrets.GMAIL_USERNAME }}
    - name: "Share today's event summary from given calendar"
      run: bundle exec rake share_calendar_events
      env:
        IDOBATA_LOUNGE:      ${{ secrets.IDOBATA_LOUNGE  }}
        GOOGLE_CALENDAR_IDS: ${{ secrets.GOOGLE_CALENDAR_IDS }}
        GOOGLE_SECRETS:      ${{ secrets.GOOGLE_SECRETS  }}
        GOOGLE_TOKENS:       ${{ secrets.GOOGLE_TOKENS   }}

    - name: Commit new article(s) from Note RSS if exists
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          git config user.name  Yohei\ Yasukawa
          git config user.email yohei@yasslab.jp
          git remote set-url origin https://yasulab:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git checkout master
          git add _data/news.yml
          git commit -m '🤖 Upsert note article(s) by GitHub Actions'
          git push origin master
        else
          echo "Nothing changes. yay ;)"
        fi
      env:
        GITHUB_TOKEN: 

#    - name: actions-idobata
#      uses: mahaker/actions-idobata@v1.1.1
#      with:
#        hookUrl: ${{ secrets.IDOBATA_GITHUB_ACTIONS }}
#        message: | # multiple lines
#          <div>
#          Test notification from Scheduler workflow in GitHub Actions. (<a href='https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'>Actions</a>)
#          </div>
#        format: 'html' # default
