name: Scheduler (Every 30 minutes)

# Spec: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule
# For debug: https://crontab.guru/
on:
  schedule:
    - cron:  '*/30 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: 'Set up Ruby'
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        #ruby-version: 2.7 # Not necessary if .ruby-version is given
    - name: "Install Ruby gems with 'actions' group"
      run: |
        bundle config set with 'actions'
        bundle config set path 'vendor/bundle'
        bundle install --jobs 4 --retry 3

    - name: 'Share fetched articles from RSS'
      run:  bundle exec rake share_rss_articles
      env:
        IDOBATA_SHARE: ${{ secrets.IDOBATA_SHARE }}

    - name: 'Upsert recent articles from note.com'
      run: |
        bundle exec rake upsert_recent_notes
        if [ -n "$(git status --porcelain)" ]; then
          echo "NEW_NOTE=true"  >> $GITHUB_ENV
        else
          echo "NEW_NOTE=false" >> $GITHUB_ENV
        fi

    - name: 'No recent articles found'
      if: ${{ env.NEW_NOTE == 'false' }}
      run: |
        echo "No recent articles found in note."

    - name: 'Deploy to Heroku if test suite passed'
      if: ${{ env.NEW_NOTE == 'true' }}
      uses: akhileshns/heroku-deploy@v3.4.6
      with:
        branch:          'master'
        usedocker:       false
        heroku_api_key:   ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: 'yasslab-jp'
        heroku_email:    'yohei@yasslab.jp'
        healthcheck:     'https://yasslab.jp/health'
