name: Scheduler (Every 30 minutes)

# Spec: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule
# For debug: https://crontab.guru/
on:
  schedule:
    - cron:  '*/30 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: 'Set up Ruby'
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        #ruby-version: 2.7 # Not necessary if .ruby-version is given
    - name: "Install Ruby gems with 'actions' group"
      run: |
        bundle config set with 'actions'
        bundle config set path 'vendor/bundle'
        bundle install --jobs 4 --retry 3

    - name: 'Share fetched articles from RSS'
      run:  bundle exec rake share_rss_articles
      env:
        IDOBATA_SHARE: ${{ secrets.IDOBATA_SHARE }}

    - name: 'Upsert recent articles from note.com'
      run: |
        bundle exec rake upsert_recent_notes
        if [ -n "$(git status --porcelain)" ]; then
          git config user.name  Yohei\ Yasukawa
          git config user.email yohei@yasslab.jp
          git remote set-url origin https://yasulab:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git checkout master
          if ( ruby -ryaml -e "p YAML.load(STDIN.read)" < _data/news.yml ); then
            git add _data/news.yml
            git commit -m '🤖 Upsert note article(s) by GitHub Actions'
            git push origin master
            git push heroku master
          else
            echo "Detected YAML syntax error in '_data/news.yml' so not deployed."
          fi
        fi
      env:
        GITHUB_TOKEN: 
